### ISSUE TITLE
"Official" Docker Docset

### ISSUE THREAD

**Issue by Kapeli** [MWers/docker-docset#2]
Hi @MWers. This is just a heads-up that a Docker docset made by me will be released in the next Dash update. Please let me know what you would like to happen with your Docker docset in the user contributed section? Should I remove it or will you continue to support it alongside my own docset? Either way is fine with me.

If you want to check out my own docset, you can grab it from http://kapeli.com/feeds/Docker.tgz. Let me know if you have any comments or notice anything wrong.

**Comment by MWers** [comment]
@Kapeli - Feel free to remove it, I created the user-contributed docset because there wasn't an official one. I'm happy to let you take it over! 

At first glance, your docset looks good. I like how the commands are broken out in the TOC.

I don't see an icon. Feel free to use this one if you like - https://raw.githubusercontent.com/MWers/docker-docset/master/assets/docset/icon%402x.png - although I'm guessing that there are higher resolution ones available.

Cheers!

**Comment by Kapeli** [comment]
Great. I'll remove your Docker docset after the next Dash update is released.

Icons for "official" docsets are included with Dash, so the icon will be shown only when Dash is updated.

**Comment by bradgessler** [comment]
@Kapeli how are these introduced into the app feeds? I'm running the latest version of Dash and the Docker docset didn't appear automatically. I had to manually add it.

**Comment by Kapeli** [comment]
@bradgessler If that happened I'm 99% sure you're not running the latest version (3.1.4).

**Comment by bradgessler** [comment]
Correct, I'm on 2.x. I emailed a while back asking if docsets would still be maintained and I was lead to believe that was the case. Not super thrilled about that because I bought 2.x a few days before 3.x was released. I get why you bumped to 3.x, but the timing was pretty bad for me. Any plans to address this? e.g. continue supporting 2.x docset feeds with the latest stuff for 1 year after the 3.x release? I'd like to at least one year of value out of Dash 2.x before upgrading.

**Comment by Kapeli** [comment]
I don't think I ever claimed that I'd add new feeds to Dash 2. What I (probably) said was that Dash 2 will still get docset updates.

If you purchased a few days before Dash 3 was released please forward me your purchase receipt as you can upgrade for free to Dash 3.
